# Generated by Django 2.1.2 on 2018-11-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('shield', models.ImageField(upload_to='')),
                ('category', models.ManyToManyField(to='tournament.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FootbalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starDate', models.DateTimeField()),
                ('homeGoals', models.IntegerField(blank=True, null=True)),
                ('awayGoals', models.IntegerField(blank=True, null=True)),
                ('homePenaltis', models.IntegerField(blank=True, null=True)),
                ('awayPenaltis', models.IntegerField(blank=True, null=True)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Category')),
                ('idClub_Category_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_category_away', to='tournament.Club')),
                ('idClub_Category_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_category_home', to='tournament.Club')),
                ('idFootbalField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.FootbalField')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGold', models.BooleanField()),
                ('idMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Matches')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Category')),
                ('idClub', models.ManyToManyField(to='tournament.Club')),
                ('idZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='playoff',
            name='idTypeOfMatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.TypeOfMatch'),
        ),
        migrations.AlterUniqueTogether(
            name='zone_category',
            unique_together={('idCategory', 'idZone')},
        ),
    ]
