# Generated by Django 2.1.2 on 2018-10-30 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('numberOfLodged', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('shield', models.ImageField(upload_to='')),
                ('category', models.ManyToManyField(to='tournament.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FootbalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldNumber', models.IntegerField()),
                ('locationField', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starDate', models.DateTimeField()),
                ('score', models.CharField(max_length=2)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Category')),
                ('idClub_Category_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_category_away', to='tournament.Club')),
                ('idClub_Category_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_category_home', to='tournament.Club')),
                ('idFootbalField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.FootbalField')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Category')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='idClub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Club'),
        ),
    ]
