# Generated by Django 2.1.2 on 2018-11-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Category')),
                ('idClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Club')),
                ('idZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Zone')),
            ],
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='idClub',
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
    ]
