# Generated by Django 2.1.2 on 2018-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='shield',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
