# Generated by Django 2.1.2 on 2018-11-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20181106_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone_category',
            name='idClub',
        ),
        migrations.AddField(
            model_name='zone_category',
            name='idClub',
            field=models.ManyToManyField(to='tournament.Club'),
        ),
    ]
