# Generated by Django 2.1.2 on 2018-11-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20181106_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footbalfield',
            name='locationField',
        ),
        migrations.AlterUniqueTogether(
            name='zone_category',
            unique_together={('idCategory', 'idZone')},
        ),
    ]
