# Generated by Django 2.1.2 on 2018-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20181115_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='score',
            field=models.CharField(max_length=20),
        ),
    ]
