# Generated by Django 2.1.2 on 2018-11-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20181115_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='score',
        ),
        migrations.AddField(
            model_name='matches',
            name='awayGoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='awayPenaltis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='homeGoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='homePenaltis',
            field=models.IntegerField(null=True),
        ),
    ]
