# Generated by Django 2.1.2 on 2018-11-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20181117_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='awayGoals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='awayPenaltis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='homeGoals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='homePenaltis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Club'),
        ),
    ]
