# Generated by Django 2.1.2 on 2018-11-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20181117_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGold', models.BooleanField()),
                ('idMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Matches')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='playoff',
            name='idTypeOfMatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.TypeOfMatch'),
        ),
    ]
